### ISSUE TITLE
Cannot Open the Revenue Sharing Section

### ISSUE THREAD

**Issue by shirgho** [FIWARE-TMForum/Business-API-Ecosystem#1] opened 2016-11-15 13:00 UTC
I have installed the Business API Ecosystem, configured it and run the server.  I have a user with all three roles, (provider, purchaser and seller). I can create catalogs, product specifications etc. However, I cannot create Product offering, as we need to have at least one Revenue Sharing model saved beforehand.

However, upon clicking the Revenue Sharing section, an error is displayed :
"An unexpected error in the RSS API prevented your request to be processed"

A sample output from the server is :

2016-11-13 02:50:11.460  - INFO: TMF - 61193f61-7f76-47b2-b0db-33f4383eab18 - ::ffff:79.194.126.95 - sameerstg - GET: /DSRevenueSharing/rss/models?providerId=sameerstg - Validating RSS provider
2016-11-13 02:50:11.575  - WARN: TMF - 61193f61-7f76-47b2-b0db-33f4383eab18 - ::ffff:79.194.126.95 - sameerstg - GET: /DSRevenueSharing/rss/models?providerId=sameerstg - Pre-Validation (DSRevenueSharing): An unexpected error in the RSS API prevented your request to be processed
2016-11-13 02:50:11.577  - WARN: Server - 61193f61-7f76-47b2-b0db-33f4383eab18 - ::ffff:79.194.126.95 - sameerstg - GET: /DSRevenueSharing/rss/models?providerId=sameerstg - Status: 500

I assume this means that it has trouble accessing the database, but the RSS database is created in mysql, and I have saved the database.properties file in the default location.

Thank you for looking through the issue.
Sameer

**Comment by fdelavega** [comment] 2016-11-15 15:27
Hi Sameer,

The default revenue sharing model, should have been created automatically when you access to the portal the first time (Indeed it seems that this is one of the requests crashing).

Did you configure and launch the charging backend? This component is in the middle of the processing and creates some initial structures.

You can try to access to the RSS database and check if the dbe_agreggator table is empty. If this is the case, means that something is missing in the charging backend configuration

Best regards,
Francisco

**Comment by shirgho** [comment] 2016-11-15 15:50
Thank you for the quick reply. I will look at it again tomorrow(laptop is at work) and reply.

**Comment by fdelavega** [comment] 2016-11-15 15:54
Additionally, if you just want to try the platform, we have an instance deployed in https://store.lab.fiware.org

**Comment by shirgho** [comment] 2016-11-17 10:50
Hi Francisco,
After configuring the charging backend at the "createsite local" step, I cannot run the charging backend server.
I configure the local site to "localhost:8004" and then run the backend at the same address.

I get the following error, copied from a longer log:
  File "/home/ubuntu/Business-API-Ecosystem/business-ecosystem-charging-backend/virtenv/local/lib/python2.7/site-packages/requests/models.py", line 884, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8080/DSProductInventory/api/productInventory/v2/hub

Previously, I was using the command ./manage.py createsite internal, instead of local. I could then start the charging backend. Will this make a difference to the configuration? Other than this, I do not think I am doing anything different in the configuration, and the dbe_agreggator is indeed empty.

Thank you again for looking through the problem!
Sameer

**Comment by shirgho** [comment] 2016-11-17 11:16
Hmmm, actually I can only run the charging backend without creating the local site first.

The "internal" keyword instead of "local" does not seem to make any difference, I remembered incorrectly, I suppose.

**Comment by fdelavega** [comment] 2016-11-17 11:20
Hi Sammer,

Sorry, this is a known bug, the problem is that glassfish 4.1.1 is crashing when a subscription is created to the inventory API due to a bug they are issuing. You can solve this by using glassfish 4.1 instead of glassfish 4.1.1

I have updated the installation script to workarround this problem, but I haven't modified the realease yet.

It is working when you don´t have an internal site, since the subscription call is not done until the charging backend is completely configured

**Comment by shirgho** [comment] 2016-11-17 11:25
Hello Francisco,

OK, I will try it out with glassfish 4.1 and report back.
Thanks.

Sameer.

**Comment by shirgho** [comment] 2016-11-17 12:20
Yup, it worked with Glassfish 4.1.

Thank you for the support!

**Comment by fdelavega** [comment] 2016-11-22 12:37
Nice! I am closing this issue, let me know if you have any other problem

**Closed by fdelavega** 2016-11-22 12:37 UTC
